# Basic Python

## 1. Split this string

In [26]:
s = "Hi there Sam!"

In [27]:
a=s.split()
print(a)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [28]:
output="The diameter of {} is {} kilometers.".format(planet,diameter)
print(output)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [29]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [30]:
x=d['k1'][3]['tricky'][3]['target'][3]
print(x)

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [31]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
np.array([5,5,5,5,5,5,5,5,5,5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [33]:
matrix=np.arange(20,36,2)
matrix

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [34]:
matrix=np.arange(0,9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [37]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
x=np.array([1,2,3])
y=np.array([4,5,6])
merge=np.concatenate((a,b))
print(merge)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [38]:
import pandas as pd


In [39]:
x={'SNo':[1,2,3],'Name':['john','cyan','max']}
x1=pd.DataFrame(x)
print(x1)

   SNo  Name
0    1  john
1    2  cyan
2    3   max


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [40]:
dates=pd.Series([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1,2,3,4,5,6,7,8,9,10])
dates

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31     1
32     2
33     3
34     4
35     5
36     6
37     7
38     8
39     9
40    10
dtype: int64

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [41]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [42]:
dframe=pd.DataFrame(lists,columns=['No','Name','Age'])
dframe

No Name  Age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24