# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [3]:
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [72]:
text="The diameter of {} is {} kilometers.".format(planet,diameter)
print(text)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [9]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [25]:
y=d['k1'][3]['tricky'][3]['target'][3]
print(y)

hello


# Numpy

In [50]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [51]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
np.array([5,5,5,5,5,5,5,5,5,5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

## 5. Create an array of all the even integers from 20 to 35

In [67]:
array=np.arange(20,36,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [66]:
array=np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [69]:
a=np.array([1,2,3])
b=np.array([4,5,6])
concat=np.concatenate((a,b))
print(concat)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [26]:
import pandas as pd


In [28]:
detail={'RegNo':[101,102,103],'Name':['AAA','BBB','CCC']}
data=pd.DataFrame(detail)
print(data)

   RegNo Name
0    101  AAA
1    102  BBB
2    103  CCC


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [39]:
data=pd.Series([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,1,2,3,4,5,6,7,8,9,10])
data

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
23    24
24    25
25    26
26    27
27    28
28    29
29    30
30    31
31     1
32     2
33     3
34     4
35     5
36     6
37     7
38     8
39     9
40    10
dtype: int64

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [40]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [48]:
data=pd.DataFrame(lists,columns=['No','Name','Age'])
data

No Name  Age
0   1  aaa   22
1   2  bbb   25
2   3  ccc   24